apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: developer-portal-runtime
  namespace: fcs-developer-portal
spec:
  infisicalAuthRef:
    name: fcs-platform-auth
    namespace: infisical-operator-system
  syncOptions:
    refreshInterval: 5m
    instantUpdates: false
  sources:
    - projectSlug: fcs-platform-dd-uk
      environmentSlug: prod
      secretPath: /developer-portal
  targets:
    - name: developer-portal-runtime
      namespace: fcs-developer-portal
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          BACKSTAGE_BACKEND_SECRET: '{{ secretFrom "/developer-portal" "backstage-backend-secret" }}'
          GITHUB_APP_ID: '{{ secretFrom "/developer-portal" "github-app-id" }}'
          GITHUB_APP_CLIENT_ID: '{{ secretFrom "/developer-portal" "github-app-client-id" }}'
          GITHUB_APP_CLIENT_SECRET: '{{ secretFrom "/developer-portal" "github-app-client-secret" }}'
          GITHUB_APP_PRIVATE_KEY: '{{ secretFrom "/developer-portal" "github-app-private-key" }}'
          MINIO_TECHDOCS_ACCESS_KEY: '{{ secretFrom "/developer-portal" "minio-techdocs-access-key" }}'
          MINIO_TECHDOCS_SECRET_KEY: '{{ secretFrom "/developer-portal" "minio-techdocs-secret-key" }}'
