apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: developer-portal-auth
  namespace: fcs-developer-portal
spec:
  basicAuth:
    secret: developer-portal-basic-auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fcs-devportal-tls
  namespace: fcs-developer-portal
spec:
  secretName: fcs-devportal-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  dnsNames:
    - fcs-devportal.flaviojcf.com.br
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fcs-developer-portal
  namespace: fcs-developer-portal
  annotations:
    kubernetes.io/ingress.class: fcs-traefik
    traefik.ingress.kubernetes.io/router.middlewares: fcs-developer-portal-developer-portal-auth@kubernetescrd
spec:
  ingressClassName: fcs-traefik
  tls:
    - hosts: [fcs-devportal.flaviojcf.com.br]
      secretName: fcs-devportal-tls
  rules:
    - host: fcs-devportal.flaviojcf.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fcs-developer-portal
                port:
                  name: http
